import { createElement } from '@lwc/engine-dom';
import Lv3_Data_Binding_And_Properties from 'c/lv3_Data_Binding_And_Properties';

describe('c-lv3-data-binding-and-properties', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lv3-data-binding-and-properties', {
            is: Lv3_Data_Binding_And_Properties
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});