/*
PushTopic pushtopic = new PushTopic();
pushtopic.Name = 'AccountUpdates';
PushTopic.Query = 'SELECT Id,Name FROM Account ';
pushTopic.ApiVersion = 59.0;
pushTopic.NotifyFroOperationCreate = true ;
pushTopic.NotifyFroOperationUpdate = true ;
pushTopic.NotifyFroOperationDelete = true ;
pushTopic.NotifyForFields = 'referenced ';
insert pushTopic;
system.debug('PushTopic created :' + pushTopic.Id);  */
