public clas Conditions{
    public static void max(){
        Integer num1 = 20 , num2 = 40; // if this line commented u can enter values at run time in the console .
        if (num1>num2){
            System.debug('Num1 is the max');
        else {
            System.debug('Num2 is tha max ');
        }        
        }
    
    public static void CheckEvenOdd (Integer num){
        if (Math.mod(num,2) == 0) {
            System.debug('is Even ');
        }else {
            System.debug('is Odd');
        }
    }


    }
}