import { createElement } from '@lwc/engine-dom';
import Lv1_Build_Custom_Contact_Card_Component from 'c/lv1_Build_Custom_Contact_Card_Component';

describe('c-lv1-build-custom-contact-card-component', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lv1-build-custom-contact-card-component', {
            is: Lv1_Build_Custom_Contact_Card_Component
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});